package com.weipai.mapper;

import java.util.List;
import java.util.Map;

import com.weipai.model.PaylogLot;
import com.weipai.model.PayloglotExt;

public interface PaylogLotMapper {
	int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylog
     *
     * @mbggenerated
     */
    int insert(PaylogLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylogLot
     *
     * @mbggenerated
     */
    int insertSelective(PaylogLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylogLot
     *
     * @mbggenerated
     */
//    List<PaylogLot> selectByExample(PaylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylog
     *
     * @mbggenerated
     */
    PaylogLot selectByPrimaryKey(Integer id);
    
    List<PaylogLot> selectByManagerId(Map<String,Object> params);
    
    
    List<PaylogLot> selectUserPaySum(Map<String,Object> params);
    
    
    int selectUserPaySumCount(Map<String,Object> params);
    
    List<PayloglotExt> selectByMidTime(Map<String,Object> params);
    
    int selectByMidTimeCount(Map<String,Object> params);
    
    
    List<PayloglotExt> selectByAllTime(Map<String,Object> params);
    
    int selectByAllTimeCount(Map<String,Object> params);
    
    
    int selectSumByManagerId(Map<String,Object> params);
    
    int sumByManagerId(Map<String,Object> params);
    
    int sumSubByManagerId(Map<String,Object> params);
    
    int sumSub2ByManagerId(Map<String,Object> params);
    
    int sumSub3ByManagerId(Map<String,Object> params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylog
     *
     * @mbggenerated
     */
//    int updateByExampleSelective(@Param("record") Paylog record, @Param("example") PaylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylog
     *
     * @mbggenerated
     */
//    int updateByExample(@Param("record") Paylog record, @Param("example") PaylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaylogLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaylogLot record);

	void tixianUpdate(Map<String, Object> params);
	void tixianDone(Map<String, Object> params);

}